# Generated by Django 5.2.5 on 2025-08-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationManager',
        ),
    ]
