# Generated by Django 5.2.5 on 2026-02-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"verbose_name": "Беседа", "verbose_name_plural": "Беседы"},
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name": "Факультет", "verbose_name_plural": "Факультеты"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterModelOptions(
            name="sectionform",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Форма направления",
                "verbose_name_plural": "Формы направлений",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="sectionform",
            name="phone",
            field=models.CharField(max_length=11),
        ),
    ]
