# Generated by Django 5.2.5 on 2026-02-12 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0002_alter_conversation_options_alter_faculty_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionform",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatapp.faculty"
            ),
        ),
    ]
